# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 8) do

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "taggings", :force => true do |t|
    t.column "tag_id",        :integer
    t.column "taggable_id",   :integer
    t.column "taggable_type", :string
    t.column "created_at",    :datetime
  end

  add_index "taggings", ["tag_id"], :name => "index_taggings_on_tag_id"
  add_index "taggings", ["taggable_id", "taggable_type"], :name => "index_taggings_on_taggable_id_and_taggable_type"

  create_table "tags", :force => true do |t|
    t.column "name", :string
  end

  create_table "task_list_users", :force => true do |t|
    t.column "task_list_id", :integer,                 :null => false
    t.column "user_id",      :integer
    t.column "read_only",    :integer,  :default => 1
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
    t.column "token",        :string
    t.column "email",        :string
  end

  add_index "task_list_users", ["task_list_id"], :name => "task_list_id"
  add_index "task_list_users", ["user_id"], :name => "user_id"

  create_table "task_lists", :force => true do |t|
    t.column "user_id",         :integer,                 :null => false
    t.column "name",            :string,                  :null => false
    t.column "description",     :string
    t.column "closed",          :integer,  :default => 0
    t.column "public",          :integer,  :default => 0
    t.column "cached_tag_list", :text
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "token",           :string
  end

  add_index "task_lists", ["user_id"], :name => "user_id"

  create_table "tasks", :force => true do |t|
    t.column "task_list_id",    :integer,                 :null => false
    t.column "user_id",         :integer
    t.column "name",            :string,                  :null => false
    t.column "description",     :string
    t.column "position",        :integer
    t.column "priority",        :integer
    t.column "closed",          :integer,  :default => 0
    t.column "starts_at",       :datetime
    t.column "ends_at",         :datetime
    t.column "cached_tag_list", :text
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
  end

  add_index "tasks", ["task_list_id"], :name => "tasks_ibfk_1"
  add_index "tasks", ["user_id"], :name => "tasks_ibfk_2"

  create_table "users", :force => true do |t|
    t.column "first_name",                :string
    t.column "first_name_for_sorting",    :string
    t.column "last_name",                 :string
    t.column "last_name_for_sorting",     :string
    t.column "language",                  :string,                 :default => "es"
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "activation_code",           :string,   :limit => 40
    t.column "activated_at",              :datetime
    t.column "is_admin",                  :integer,                :default => 0
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "active_task_list_1_id",     :integer
    t.column "active_task_list_2_id",     :integer
    t.column "active_task_list_3_id",     :integer
    t.column "active_task_list_4_id",     :integer
    t.column "chpass_token",              :string
    t.column "beruby_visited",            :integer,                :default => 0
  end

  add_index "users", ["active_task_list_1_id"], :name => "active_task_list_1_id"
  add_index "users", ["active_task_list_2_id"], :name => "active_task_list_2_id"
  add_index "users", ["active_task_list_3_id"], :name => "active_task_list_3_id"
  add_index "users", ["active_task_list_4_id"], :name => "active_task_list_4_id"

end
